### ISSUE TITLE
Does not work and does not compile

### ISSUE THREAD

**Issue by woodholly** [php-translation/cli#3]
box and php-scoper updated to latest versions

make builds fails with:
Could not scan for classes inside "app/AppKernel.php" which does not appear to be a file nor a folder

**Comment by bocharsky-bw** [comment]
Hm, that sounds weird to me. Are you sure you have that `app/AppKernel.php` file? Because that file exists in this repository. I suppose you run `make build`, did you run it from the root directory of this repo? If you could give more detailed steps to reproduce - it may help a lot. Also, if you have a solution - please, feel free to send a PR

**Comment by woodholly** [comment]
I tried to guess how should I setup the development environment (../ paths outside the project is not very popular you know ..) and just replaced required those external utilities with static versions, and failed with this error
@bocharsky-bw I can’t even try this program, and you ask for a solution :)
